

sqlexport:
#[sort column]可选字段：TABLE_NAME（表名）、TABLE_TYPE（表类型）、TABLE_COMMENT（表注释）
  tableSort: 'TABLE_TYPE,TABLE_NAME'
  tableSortDesc: false
  exportName: 'D:\\test.md'
  databaseName: 'cs_admin_db_v2'
  textStartLevel: '2'
  textstartIndex: '3'

spring:
  datasource:
    url: jdbc:mysql://111.229.232.161:9306/information_schema?useSSL=false&useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useTimezone=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: by-user
    password: By-user2020


# MyBatis
mybatis-plus:
  mapper-locations: classpath*:/mapping/**/*.xml
  typeAliasesPackage: com.example.demo.domain
  global-config:
    id-type: 3  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  port: 9090
